### ISSUE TITLE
dbWriteTable with temporary tables

### ISSUE THREAD

**Issue by gaborcsardi** [r-dbi/RMySQL#10]
`dbWriteTable(..., append=TRUE)` unfortunately does not work with temporary tables. I guess this is because it checks if the table exists, and this check ignores temporary tables. 

What happens is, that a proper table is created, even if there is already a temporary table with the same name (assuming the user has rights to create real tables).

This is really unfortunate, because temporary tables could be a workaround of the lack of ability to bind to a data frame, or create a prepared query.....

Here is the code to reproduce it, sorry, it is not self-contained, you would need a DB connection, obviously:

```
dbSendQuery(con, "CREATE TEMPORARY TABLE tmp (foobar TEXT);")
dbWriteTable(con, "tmp", data.frame(foobar=letters[1:5]), 
                     row.names=FALSE, append=TRUE)
```

The solution is probably to check for temporary tables, too, via 

```
show temporary tables;
```

**Comment by Rich1000** [comment]
I also prefer the last solution (fail if table doesn't exist) and would be mega happy to see this in an update :)

**Comment by lrob** [comment]
I would like to append data to a temporary table. Unfortunately I'm experiencing the same problem that @gaborcsardi described at the beginning of this thread.

Is this problem been solved? is it somehow possible to write a dataframe to a temporary table with RMySQL?

**Comment by krlmlr** [comment]
Could you give the new RMariaDB package a try? Just use `RMariaDB::MariaDB()` instead of `RMySQL::MySQL()` when connecting.

**Comment by lrob** [comment]
Thanks, it's working passing `temporary=T` to the `dbWriteTable`. Just one more question, can you explain me why it gives me the following warning when I execute the `dbDisconnect` function? 

```
In connection_release(conn@ptr) : There is a result object still in use.
The connection will be automatically released when it is closed
```
This is the code I execute:

```R
con <- dbConnect(drv = dbDriver("MariaDB"), dbname=tmp_dbname, user=user, password=mysql_password)

rs <- dbWriteTable(con, "sez_selected", sez_selected, temporary=T)
rs <- dbSendQuery(con, "SELECT SUM(istat.P1) as population
                     FROM sez_selected AS gis
                  INNER JOIN istat.sez_2011 as istat
                  ON  gis.codice11 = istat.CODICE11_GIS")
population <- dbFetch(rs,n=-1)
dbDisconnect(con)
```

**Comment by krlmlr** [comment]
Looks like you need `dbClearResult(rs)` before `dbDisconnect(con)` .

**Comment by lrob** [comment]
Thanks, the code now works as expected and without giving any warning.
