### ISSUE TITLE
dbWriteTable error when there are capitalized characters in table name

### ISSUE THREAD

**Issue by haozhu233** [r-dbi/RMySQL#164]
Hi, I came across this bug and I think it's probably related with 2 unresolved issues #76 and #82.

Reproducible example

``` r
# When you run the following code for the first time, it's fine. 
 dbWriteTable(myconnection, "Mtcars", mtcars, row.names = F)
> TRUE

# However, if you want to append or overwrite the table you just created,
# you will be in trouble.
 dbWriteTable(myconnection, "Mtcars", mtcars, row.names = F, append = T)
> Error in .local(conn, statement, ...) : 
> could not run statement: Table 'mtcars' already exists
```

Maybe you can add a `tolower` around the table name to lower it in R first.

**Comment by krlmlr** [comment]
Thanks, and sorry for the slow reply. Have you installed RMySQL from CRAN or from GitHub?

**Comment by andoomcz** [comment]
I ran into the same issue.  I installed RMySQL from CRAN. The R version is 3.6.2, and RMySQL version is 0.10.17. It is running on Windows 10 x64.

**Comment by haozhu233** [comment]
@andoomcz Today you are recommended to use mariadb instead as your mysql driver

https://db.rstudio.com/databases/my-sql/
