### ISSUE TITLE
dbplyr operations not work for RMySQL backend

### ISSUE THREAD

**Issue by kongdd** [r-dbi/RMySQL#230]
```R
r$> con
<MySQLConnection:0,1>

r$> copy_to(con, mtcars)
Error in `db_copy_to()`:
! Can't copy to table "mtcars"
Caused by error in `dplyr::db_write_table()`:
! Can't write table "mtcars".
Caused by error in `.local()`:
! could not run statement: Table 'ChinaMet.`mtcars`' doesn't exist
Run `rlang::last_trace()` to see where the error occurred.  

r$> rlang::last_trace()
<error/rlang_error>
Error in `db_copy_to()`:
! Can't copy to table "mtcars"
Caused by error in `dplyr::db_write_table()`:
! Can't write table "mtcars".
Caused by error in `.local()`:
! could not run statement: Table 'mtcars' already exists
---
Backtrace:
     ▆
  1. ├─dplyr::copy_to(con, mtcars)
  2. └─dplyr:::copy_to.DBIConnection(con, mtcars)
  3.   ├─dplyr::copy_to(...)
  4.   └─dbplyr:::copy_to.src_sql(...)
  5.     ├─dbplyr::db_copy_to(...)
  6.     └─dbplyr:::db_copy_to.DBIConnection(...)
  7.       ├─dbplyr:::with_transaction(...)
  8.       ├─base::tryCatch(...)
  9.       │ └─base (local) tryCatchList(expr, classes, parentenv, handlers)      
 10.       │   └─base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]]) 
 11.       │     └─base (local) doTryCatch(return(expr), name, parentenv, handler)
 12.       ├─dplyr::db_write_table(...)
 13.       └─dbplyr:::db_write_table.DBIConnection(...)
```

**Comment by jeroen** [comment]
Can you try https://github.com/r-dbi/RMariaDB instead

**Comment by kongdd** [comment]
I tried [RMariaDB](https://github.com/r-dbi/RMariaDB). RMariaDB is about 5 times slower thant RMySQL, or even slower, or died. Hence, RMySQL is more promising for me.

I found where is the bug. It can be easily fixed.

**Comment by krlmlr** [comment]
I'd like to learn where RMariaDB is slower so that we can improve. RMariaDB is the newer development, and easier to maintain because it's C++.

**Comment by kongdd** [comment]
I am using the dbplyr of the version <https://github.com/tidyverse/dbplyr/pull/1376>. So, `copy_to` also works for `RMySQL`.

**Comment by krlmlr** [comment]
Thanks. Can you please try `dbConnect(load_data_local_infile = TRUE)` with RMariaDB?

**Comment by kongdd** [comment]
Amazing, much faster now.
```R
r$> system.time({
  copy_to(con_mariadb, st_met2481, "temp02", overwrite=TRUE, indexes=c("site"))
})
   user  system elapsed 
   0.70    0.25    1.53 
```

**Comment by krlmlr** [comment]
Interesting. How does the timing differ for various data sizes?

**Comment by kongdd** [comment]
@krlmlr could you give some clue, why `table_ident_to_id(table)` not work for `RMySQL`. 
I am a new learner of `DBI`. I really can't figure out.

<https://github.com/kongdd/dbplyr/commit/d9dd0e91594ecbb8666a708057ec498203c3e675>

**Comment by kongdd** [comment]
`df` is 2,376,241 rows and 300Mb. For large data, their performance is much closer.

```R
system.time({
  copy_to(con_mysql, df, "temp01", overwrite=TRUE, indexes=c("site"))
})

   user  system elapsed
  77.00    2.45  126.28
```

```R
r$> system.time({
  copy_to(con_mariadb, df, "temp02", overwrite=TRUE, indexes=c("site"))
})
   user  system elapsed 
  55.39    5.81  145.72
```

Just wondering why the progress info disappear for large data in `mariadb`.

**Comment by krlmlr** [comment]
Loading data now uses the same mechanism (`LOAD DATA LOCAL INFILE`) in both packages. Both have to write a temporary CSV file first, both use different methods to do so.

RMariaDB uses:

```r
  readr::write_delim(
    csv_quote(value, warn_factor, conn), file, quote = "none", delim = "\t", na = "\\N",
    col_names = FALSE
  )
```

where `csv_quote()` is an internal function that converts data to strings.

RMySQL uses a variant of `write.table()` .

Chances are that the conversion code in RMariaDB is to blame. Would you mind running `profvis::profvis()` with loading a medium-size file with RMariaDB (100k rows) and sharing the results?

**Comment by kongdd** [comment]
When removed indexes:, 
```R
r$>
system.time({
  copy_to(con_mysql, df, "temp01", overwrite=TRUE)
})
   user  system elapsed 
  76.64    2.60  113.63

r$> system.time({
  copy_to(con_mariadb, df, "temp02", overwrite=TRUE)
})
   user  system elapsed 
  55.33    5.39  142.45
```

Meanwhile, I faced with another issue. It seems that `  copy_to(con_mariadb, df, "temp02", overwrite=TRUE)` didn't copy data into temp02 after runing the above cmd. 

![image](https://github.com/r-dbi/RMySQL/assets/9815742/36258bfd-72a1-4453-85d3-78b7401ab9c3)

**Comment by krlmlr** [comment]
Do you need `temporary = FALSE` ?

**Comment by kongdd** [comment]
Thank u. I will have a try

**Comment by kongdd** [comment]
Thank u @krlmlr . This parameter works for me. The current solution is acceptable. 
I am uploading a 5 GB data.frame to mariadb. Hope it would succeed tomorrow. 

Thanks for your patient guidances.

**Comment by kongdd** [comment]
This is the final used time (56,000,000 rows and 5GB data):

   user  system elapsed
 230.61   31.61 1546.50.

Although this time is tens times slower than `data.table::fwrite`, it is acceptable now.

Thank you r-dbi developers.

**Comment by krlmlr** [comment]
Thanks @kongdd for your patience and persistence. The difference between user and elapsed time suggests that most of the time is spent waiting (for the database server?) and that there's little we can do on the library side. If we reduced the cost of creating the CSV file to zero, we would still spend 1200 seconds instead of 1546, this gain seems too limited to justify the investment of reviewing faster CSV writing options.
